import { redact } from "../redact.ts";
import { normalizeYouTubeError, redactedYouTubeError } from "./errors.ts";

const API = "https://www.googleapis.com/youtube/v3";
export type RemoteYouTubeVideo = { videoId: string; title: string; description: string; tags: string[]; publishedAt: string | null; thumbnailUrl: string | null; privacyStatus: "public" | "private" | "unlisted"; views: number; likes: number; comments: number };
export type VideoMetadata = { title: string; description: string; tags: string[]; privacyStatus: "public" | "private" | "unlisted" };

export async function listRemoteVideos(options: { accessToken: string; pageToken?: string; fetch?: typeof fetch }): Promise<{ videos: RemoteYouTubeVideo[]; nextPageToken: string | null }> {
  const fetchImpl = options.fetch ?? fetch; const channel = await request(fetchImpl, `${API}/channels?${new URLSearchParams({ part: "contentDetails", mine: "true" })}`, options.accessToken); const uploads = stringValue((channel.items?.[0] as any)?.contentDetails?.relatedPlaylists?.uploads); if (!uploads) return { videos: [], nextPageToken: null };
  const params = new URLSearchParams({ part: "contentDetails", playlistId: uploads, maxResults: "50" }); if (options.pageToken) params.set("pageToken", options.pageToken); const playlist = await request(fetchImpl, `${API}/playlistItems?${params}`, options.accessToken); const ids = (playlist.items ?? []).map((item: any) => item?.contentDetails?.videoId).filter((id: unknown): id is string => typeof id === "string"); if (!ids.length) return { videos: [], nextPageToken: stringOrNull(playlist.nextPageToken) };
  const details = await request(fetchImpl, `${API}/videos?${new URLSearchParams({ part: "snippet,status,statistics", id: ids.join(",") })}`, options.accessToken); return { videos: (details.items ?? []).map(normalizeVideo).filter(Boolean) as RemoteYouTubeVideo[], nextPageToken: stringOrNull(playlist.nextPageToken) };
}

export async function getRemoteVideo(options: { accessToken: string; videoId: string; fetch?: typeof fetch }): Promise<RemoteYouTubeVideo> { const payload = await request(options.fetch ?? fetch, `${API}/videos?${new URLSearchParams({ part: "snippet,status,statistics", id: options.videoId })}`, options.accessToken); const normalized = normalizeVideo(payload.items?.[0]); if (!normalized) throw new Error("youtube-video-not-found: The YouTube video was not found."); return normalized; }
export async function updateRemoteVideo(options: { accessToken: string; videoId: string; metadata: VideoMetadata; fetch?: typeof fetch }): Promise<RemoteYouTubeVideo> { validateMetadata(options.metadata); const payload = await request(options.fetch ?? fetch, `${API}/videos?part=snippet,status`, options.accessToken, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: options.videoId, snippet: { title: options.metadata.title, description: options.metadata.description, tags: options.metadata.tags }, status: { privacyStatus: options.metadata.privacyStatus } }) }); const normalized = normalizeVideo(payload.items?.[0] ?? payload); if (!normalized) throw new Error("youtube-video-not-found: The YouTube video was not found."); return normalized; }
export async function deleteRemoteVideo(options: { accessToken: string; videoId: string; confirm: boolean; fetch?: typeof fetch }): Promise<void> { if (options.confirm !== true) throw new Error("youtube-confirmation-required: Set confirm to true to delete the remote video."); const response = await (options.fetch ?? fetch)(`${API}/videos?id=${encodeURIComponent(options.videoId)}`, { method: "DELETE", headers: { authorization: `Bearer ${options.accessToken}` } }); if (!response.ok) throw new Error(`${normalizeYouTubeError({ response: { status: response.status, body: redact(await response.text()) } }).code}: YouTube video deletion failed.`); }

export function validateMetadata(metadata: VideoMetadata): void { if (!metadata || typeof metadata.title !== "string" || metadata.title.trim().length === 0 || metadata.title.length > 100 || typeof metadata.description !== "string" || metadata.description.length > 5000 || !Array.isArray(metadata.tags) || metadata.tags.some((tag) => typeof tag !== "string" || tag.length > 500) || !isPrivacy(metadata.privacyStatus)) throw new Error("youtube-invalid-metadata: Title, description, tags, and privacy status are invalid."); }

async function request(fetchImpl: typeof fetch, url: string, accessToken: string, init: RequestInit = {}): Promise<any> { let response: Response; try { response = await fetchImpl(url, { ...init, headers: { authorization: `Bearer ${accessToken}`, ...init.headers } }); } catch (error) { throw redactedYouTubeError(error); } if (!response.ok) { const body = redact(await response.text()); const mapped = normalizeYouTubeError({ response: { status: response.status, body } }); throw new Error(`${mapped.code}: ${mapped.message}`); } try { return await response.json(); } catch { throw new Error("youtube-upload-failed: YouTube returned an invalid response."); } }
function normalizeVideo(item: any): RemoteYouTubeVideo | null { if (!item || typeof item.id !== "string") return null; const snippet = item.snippet ?? {}; const stats = item.statistics ?? {}; const privacy = isPrivacy(item.status?.privacyStatus) ? item.status.privacyStatus : "private"; return { videoId: item.id, title: stringValue(snippet.title), description: stringValue(snippet.description), tags: Array.isArray(snippet.tags) ? snippet.tags.filter((tag: unknown): tag is string => typeof tag === "string") : [], publishedAt: stringOrNull(snippet.publishedAt), thumbnailUrl: stringOrNull(snippet.thumbnails?.default?.url), privacyStatus: privacy, views: count(stats.viewCount), likes: count(stats.likeCount), comments: count(stats.commentCount) }; }
function isPrivacy(value: unknown): value is RemoteYouTubeVideo["privacyStatus"] { return value === "public" || value === "private" || value === "unlisted"; }
function stringValue(value: unknown): string { return typeof value === "string" ? value : ""; }
function stringOrNull(value: unknown): string | null { return typeof value === "string" && value ? value : null; }
function count(value: unknown): number { const n = Number(value); return Number.isFinite(n) && n >= 0 ? n : 0; }
